# Generated by Django 5.2.7 on 2025-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
