# Generated by Django 5.2.8 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lesson_content_lesson_pdf_url_lesson_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactSubmission',
        ),
        migrations.RenameField(
            model_name='userlevelprogress',
            old_name='correct_count',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='userlevelprogress',
            name='wrong_questions_ids',
        ),
        migrations.AddField(
            model_name='userlevelprogress',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
