# Generated by Django 5.2.8 on 2025-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_contact_contactsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_includes',
            field=models.TextField(default='Access on mobile\nCertificate of completion'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='curriculum',
            field=models.TextField(default='Introduction - 10 mins\nGetting Started - 15 mins'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='2 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='what_you_will_learn',
            field=models.TextField(default='Basics of the subject\nCore concepts\nPractical examples'),
        ),
    ]
